import type { CommunityPreset } from '../types'

export const associationPreset: CommunityPreset = {
  type: 'association',
  displayName: 'Asociación',
  description: 'Asociaciones civiles, cámaras, colegios profesionales',
  icon: 'users',
  labels: {
    member: 'Asociado',
    memberPlural: 'Asociados',
    contribution: 'Cuota de asociado',
    leader: 'Presidente',
    entity: 'Proveedor',
    community: 'Asociación',
    assembly: 'Asamblea general',
    oversight: 'Comisión revisora',
  },
  defaultRules: {
    governance: {
      default_quorum: 0.5,
      default_majority: 0.5,
      delegation_enabled: true,
      proposal_rights: ['admin', 'comite_vigilancia', 'tesorero', 'miembro'],
      cool_down_hours: 48,
      auto_execution_enabled: false,
      auto_execution_threshold: 0,
      mandatory_discussion_enabled: true,
      default_discussion_hours: 72,
      grace_period_hours: 24,
      quorum_by_type: {
        ordinary: 0.5,
        extraordinary: 0.66,
        budget: 0.5,
        election: 0.5,
        amendment: 0.66,
      },
      majority_by_type: {
        ordinary: 0.5,
        extraordinary: 0.66,
        budget: 0.5,
        election: 0.5,
        amendment: 0.66,
      },
      min_endorsements: 2,
      endorsement_bypass_roles: ['admin'],
      quorum_first_call: 0.5,
      quorum_second_call: 0.33,
      quorum_third_call: 0,
      minimum_notice_days: 7,
      quarterly_assembly_required: false,
      extraordinary_quorum: 0.66,
    },
    treasury: {
      mode: 'import',
      locale: 'es-MX',
      currency: 'MXN',
      admin_spending_limit: 30000,
      require_vote_above: 50000,
      clabe: null,
      bank_name: null,
      beneficiary_name: null,
      payment_reference_prefix: null,
      auto_reconciliation: false,
      collection_reminder_days: 7,
      reserva_fund_percentage: 0,
      monthly_statement_auto: true,
    },
    identity: {
      payment_to_vote_enabled: true,
      grace_period_months: 3,
      auto_restore_on_payment: true,
      delinquent_restrictions: ['vote'],
      moroso_threshold_ordinary: 3,
      moroso_threshold_extraordinary: 1,
      moroso_notice_days: 10,
      moroso_restrictions: ['vote', 'be_elected'],
      admin_max_consecutive_terms: 2,
      admin_term_months: 24,
    },
  },
  defaultCategories: [
    { name: 'Cuotas de asociados', type: 'income', isSystem: true },
    { name: 'Cuotas extraordinarias', type: 'income', isSystem: false },
    { name: 'Eventos y congresos', type: 'income', isSystem: false },
    { name: 'Patrocinios', type: 'income', isSystem: false },
    { name: 'Otros ingresos', type: 'income', isSystem: false },
    { name: 'Eventos y actividades', type: 'expense', isSystem: false },
    { name: 'Personal administrativo', type: 'expense', isSystem: false },
    { name: 'Oficina y operación', type: 'expense', isSystem: false },
    { name: 'Comunicación', type: 'expense', isSystem: false },
    { name: 'Servicios profesionales', type: 'expense', isSystem: false },
  ],
  enabledModules: [
    'documents',
    'announcements',
    'calendar',
    'census',
  ],
  legalFrameworkKey: 'mx.ac',
}
