import type { CommunityPreset } from '../types'

export const clubPreset: CommunityPreset = {
  type: 'club',
  displayName: 'Club',
  description: 'Clubes deportivos, sociales, culturales',
  icon: 'trophy',
  labels: {
    member: 'Socio',
    memberPlural: 'Socios',
    contribution: 'Membresía',
    leader: 'Presidente',
    entity: 'Proveedor',
    community: 'Club',
    assembly: 'Asamblea general',
    oversight: 'Comisión revisora',
  },
  defaultRules: {
    governance: {
      default_quorum: 0.33,
      default_majority: 0.5,
      delegation_enabled: true,
      proposal_rights: ['admin', 'comite_vigilancia', 'miembro'],
      cool_down_hours: 24,
      auto_execution_enabled: false,
      auto_execution_threshold: 0,
      mandatory_discussion_enabled: true,
      default_discussion_hours: 72,
      grace_period_hours: 24,
      quorum_by_type: {
        ordinary: 0.33,
        extraordinary: 0.5,
        budget: 0.5,
        election: 0.5,
        amendment: 0.66,
        gasto: 0.5,
      },
      majority_by_type: {
        ordinary: 0.5,
        extraordinary: 0.5,
        budget: 0.5,
        election: 0.5,
        amendment: 0.66,
        gasto: 0.5,
      },
      min_endorsements: 2,
      endorsement_bypass_roles: ['admin'],
      quorum_first_call: 0.5,
      quorum_second_call: 0.33,
      quorum_third_call: 0,
      minimum_notice_days: 5,
      quarterly_assembly_required: false,
      extraordinary_quorum: 0.5,
    },
    treasury: {
      mode: 'import',
      locale: 'es-MX',
      currency: 'MXN',
      admin_spending_limit: 20000,
      require_vote_above: 20000,
      clabe: null,
      bank_name: null,
      beneficiary_name: null,
      payment_reference_prefix: null,
      auto_reconciliation: false,
      collection_reminder_days: 7,
      reserva_fund_percentage: 0,
      monthly_statement_auto: false,
    },
    identity: {
      payment_to_vote_enabled: true,
      grace_period_months: 3,
      auto_restore_on_payment: true,
      delinquent_restrictions: ['vote'],
      moroso_threshold_ordinary: 3,
      moroso_threshold_extraordinary: 1,
      moroso_notice_days: 10,
      moroso_restrictions: ['vote', 'be_elected'],
      admin_max_consecutive_terms: 0, // sin límite, según estatutos
      admin_term_months: 24,
    },
  },
  defaultCategories: [
    { name: 'Membresías', type: 'income', isSystem: true },
    { name: 'Inscripciones', type: 'income', isSystem: false },
    { name: 'Eventos', type: 'income', isSystem: false },
    { name: 'Donaciones', type: 'income', isSystem: false },
    { name: 'Otros ingresos', type: 'income', isSystem: false },
    { name: 'Instalaciones', type: 'expense', isSystem: false },
    { name: 'Personal', type: 'expense', isSystem: false },
    { name: 'Eventos y actividades', type: 'expense', isSystem: false },
    { name: 'Equipo deportivo', type: 'expense', isSystem: false },
    { name: 'Administración', type: 'expense', isSystem: false },
  ],
  enabledModules: [
    'documents',
    'announcements',
    'calendar',
    'gamification',
  ],
  legalFrameworkKey: 'mx.ac',
}
