import type { CommunityPreset } from '../types'

export const cooperativePreset: CommunityPreset = {
  type: 'cooperative',
  displayName: 'Cooperativa',
  description: 'Cooperativas de producción, consumo, ahorro y préstamo',
  icon: 'handshake',
  labels: {
    member: 'Cooperativista',
    memberPlural: 'Cooperativistas',
    contribution: 'Aportación social',
    leader: 'Presidente del consejo',
    entity: 'Proveedor',
    community: 'Cooperativa',
    assembly: 'Asamblea general',
    oversight: 'Consejo de vigilancia',
  },
  defaultRules: {
    governance: {
      default_quorum: 0.5,
      default_majority: 0.5,
      delegation_enabled: false, // LGSC Art. 16: un socio, un voto, intransferible
      proposal_rights: ['admin', 'comite_vigilancia', 'tesorero', 'miembro'],
      cool_down_hours: 48,
      auto_execution_enabled: false,
      auto_execution_threshold: 0,
      mandatory_discussion_enabled: true,
      default_discussion_hours: 72,
      grace_period_hours: 24,
      quorum_by_type: {
        ordinary: 0.5,
        extraordinary: 0.75,
        budget: 0.66,
        election: 0.5,
        amendment: 0.75,
        gasto: 0.5,
      },
      majority_by_type: {
        ordinary: 0.5,
        extraordinary: 0.66,
        budget: 0.66,
        election: 0.5,
        amendment: 0.75,
        gasto: 0.5,
      },
      min_endorsements: 3,
      endorsement_bypass_roles: ['admin'],
      quorum_first_call: 0.75,
      quorum_second_call: 0.5,
      quorum_third_call: 0.33,
      minimum_notice_days: 7,
      quarterly_assembly_required: false,
      extraordinary_quorum: 0.75,
    },
    treasury: {
      mode: 'import',
      locale: 'es-MX',
      currency: 'MXN',
      admin_spending_limit: 20000,
      require_vote_above: 50000,
      clabe: null,
      bank_name: null,
      beneficiary_name: null,
      payment_reference_prefix: null,
      auto_reconciliation: false,
      collection_reminder_days: 5,
      reserva_fund_percentage: 10, // LGSC: fondo de reserva obligatorio
      monthly_statement_auto: true,
    },
    identity: {
      payment_to_vote_enabled: true,
      grace_period_months: 2,
      auto_restore_on_payment: true,
      delinquent_restrictions: ['vote', 'propose'],
      moroso_threshold_ordinary: 2,
      moroso_threshold_extraordinary: 1,
      moroso_notice_days: 7,
      moroso_restrictions: ['vote', 'be_elected', 'quorum_excluded'],
      admin_max_consecutive_terms: 1, // LGSC: rotación de cargos
      admin_term_months: 36,
    },
  },
  defaultCategories: [
    { name: 'Aportaciones sociales', type: 'income', isSystem: true },
    { name: 'Certificados de aportación', type: 'income', isSystem: true },
    { name: 'Ingresos por actividad', type: 'income', isSystem: false },
    { name: 'Otros ingresos', type: 'income', isSystem: false },
    { name: 'Fondo de reserva', type: 'expense', isSystem: true },
    { name: 'Fondo de previsión social', type: 'expense', isSystem: true },
    { name: 'Fondo de educación cooperativa', type: 'expense', isSystem: true },
    { name: 'Operación', type: 'expense', isSystem: false },
    { name: 'Personal', type: 'expense', isSystem: false },
    { name: 'Administración', type: 'expense', isSystem: false },
  ],
  enabledModules: [
    'documents',
    'announcements',
    'calendar',
    'census',
  ],
  legalFrameworkKey: 'mx.cooperativa',
}
