import type { CommunityPreset } from '../types'

export const customPreset: CommunityPreset = {
  type: 'custom',
  displayName: 'Personalizado',
  description: 'Define tu propia estructura desde cero',
  icon: 'settings',
  labels: {
    member: 'Miembro',
    memberPlural: 'Miembros',
    contribution: 'Contribución',
    leader: 'Administrador',
    entity: 'Entidad externa',
    community: 'Comunidad',
    assembly: 'Asamblea',
    oversight: 'Comité de revisión',
  },
  defaultRules: {
    governance: {
      default_quorum: 0.5,
      default_majority: 0.5,
      delegation_enabled: true,
      proposal_rights: ['admin', 'comite_vigilancia', 'tesorero', 'miembro'],
      cool_down_hours: 24,
      auto_execution_enabled: false,
      auto_execution_threshold: 0,
      mandatory_discussion_enabled: false,
      default_discussion_hours: 48,
      grace_period_hours: 0,
      quorum_by_type: {
        ordinary: 0.5,
        extraordinary: 0.5,
        budget: 0.5,
        election: 0.5,
        amendment: 0.66,
        gasto: 0.5,
      },
      majority_by_type: {
        ordinary: 0.5,
        extraordinary: 0.5,
        budget: 0.5,
        election: 0.5,
        amendment: 0.66,
        gasto: 0.5,
      },
      min_endorsements: 0,
      endorsement_bypass_roles: ['admin'],
      quorum_first_call: 0.5,
      quorum_second_call: 0.33,
      quorum_third_call: 0,
      minimum_notice_days: 3,
      quarterly_assembly_required: false,
      extraordinary_quorum: 0.5,
    },
    treasury: {
      mode: 'import',
      locale: 'es-MX',
      currency: 'MXN',
      admin_spending_limit: 10000,
      require_vote_above: 50000,
      clabe: null,
      bank_name: null,
      beneficiary_name: null,
      payment_reference_prefix: null,
      auto_reconciliation: false,
      collection_reminder_days: 7,
      reserva_fund_percentage: 0,
      monthly_statement_auto: false,
    },
    identity: {
      payment_to_vote_enabled: false,
      grace_period_months: 3,
      auto_restore_on_payment: true,
      delinquent_restrictions: [],
      moroso_threshold_ordinary: 3,
      moroso_threshold_extraordinary: 2,
      moroso_notice_days: 0,
      moroso_restrictions: [],
      admin_max_consecutive_terms: 0,
      admin_term_months: 12,
    },
  },
  defaultCategories: [
    { name: 'Contribuciones', type: 'income', isSystem: true },
    { name: 'Otros ingresos', type: 'income', isSystem: false },
    { name: 'Operación', type: 'expense', isSystem: false },
    { name: 'Administración', type: 'expense', isSystem: false },
    { name: 'Otros gastos', type: 'expense', isSystem: false },
  ],
  enabledModules: [
    'documents',
    'announcements',
    'calendar',
  ],
  legalFrameworkKey: null,
}
