import type { CommunityPreset } from '../types'

export const ngoPreset: CommunityPreset = {
  type: 'ngo',
  displayName: 'ONG / Fundación',
  description: 'Organizaciones no gubernamentales, fundaciones, donatarias',
  icon: 'heart-handshake',
  labels: {
    member: 'Miembro',
    memberPlural: 'Miembros',
    contribution: 'Aportación',
    leader: 'Director ejecutivo',
    entity: 'Aliado',
    community: 'Organización',
    assembly: 'Asamblea de asociados',
    oversight: 'Consejo de administración',
  },
  defaultRules: {
    governance: {
      default_quorum: 0.5,
      default_majority: 0.5,
      delegation_enabled: true,
      proposal_rights: ['admin', 'comite_vigilancia', 'miembro'],
      cool_down_hours: 48,
      auto_execution_enabled: false,
      auto_execution_threshold: 0,
      mandatory_discussion_enabled: true,
      default_discussion_hours: 120,
      grace_period_hours: 48,
      quorum_by_type: {
        ordinary: 0.5,
        extraordinary: 0.66,
        budget: 0.66,
        election: 0.5,
        amendment: 0.75,
        gasto: 0.5,
      },
      majority_by_type: {
        ordinary: 0.5,
        extraordinary: 0.66,
        budget: 0.66,
        election: 0.5,
        amendment: 0.75,
        gasto: 0.5,
      },
      min_endorsements: 3,
      endorsement_bypass_roles: ['admin'],
      quorum_first_call: 0.66,
      quorum_second_call: 0.5,
      quorum_third_call: 0.33,
      minimum_notice_days: 10,
      quarterly_assembly_required: false,
      extraordinary_quorum: 0.66,
    },
    treasury: {
      mode: 'import',
      locale: 'es-MX',
      currency: 'MXN',
      admin_spending_limit: 25000,
      require_vote_above: 50000,
      clabe: null,
      bank_name: null,
      beneficiary_name: null,
      payment_reference_prefix: null,
      auto_reconciliation: false,
      collection_reminder_days: 0,
      reserva_fund_percentage: 10,
      monthly_statement_auto: true,
    },
    identity: {
      payment_to_vote_enabled: false,
      grace_period_months: 3,
      auto_restore_on_payment: true,
      delinquent_restrictions: [],
      moroso_threshold_ordinary: 3,
      moroso_threshold_extraordinary: 1,
      moroso_notice_days: 0,
      moroso_restrictions: [],
      admin_max_consecutive_terms: 2,
      admin_term_months: 24,
    },
  },
  defaultCategories: [
    { name: 'Donativos deducibles', type: 'income', isSystem: true },
    { name: 'Donativos no deducibles', type: 'income', isSystem: false },
    { name: 'Cuotas de asociados', type: 'income', isSystem: true },
    { name: 'Fondos gubernamentales', type: 'income', isSystem: false },
    { name: 'Fondos internacionales', type: 'income', isSystem: false },
    { name: 'Venta de servicios', type: 'income', isSystem: false },
    { name: 'Programas y proyectos', type: 'expense', isSystem: false },
    { name: 'Personal', type: 'expense', isSystem: false },
    { name: 'Oficina y administración', type: 'expense', isSystem: false },
    { name: 'Comunicación y difusión', type: 'expense', isSystem: false },
    { name: 'Viáticos y transporte', type: 'expense', isSystem: false },
    { name: 'Reportes CLUNI/SAT', type: 'expense', isSystem: true },
  ],
  enabledModules: [
    'documents',
    'announcements',
    'calendar',
    'census',
  ],
  legalFrameworkKey: 'mx.donataria',
}
