import type { CommunityPreset } from '../types'

export const religiousPreset: CommunityPreset = {
  type: 'religious',
  displayName: 'Comunidad religiosa',
  description: 'Iglesias, templos, congregaciones, comunidades de fe',
  icon: 'church',
  labels: {
    member: 'Feligrés',
    memberPlural: 'Feligreses',
    contribution: 'Diezmo',
    leader: 'Pastor',
    entity: 'Colaborador',
    community: 'Iglesia',
    assembly: 'Asamblea congregacional',
    oversight: 'Consejo de ancianos',
  },
  defaultRules: {
    governance: {
      default_quorum: 0.25,
      default_majority: 0.5,
      delegation_enabled: false,
      proposal_rights: ['admin', 'comite_vigilancia'],
      cool_down_hours: 24,
      auto_execution_enabled: false,
      auto_execution_threshold: 0,
      mandatory_discussion_enabled: false,
      default_discussion_hours: 72,
      grace_period_hours: 0,
      quorum_by_type: {
        ordinary: 0.25,
        extraordinary: 0.5,
        budget: 0.33,
        election: 0.5,
        amendment: 0.5,
      },
      majority_by_type: {
        ordinary: 0.5,
        extraordinary: 0.66,
        budget: 0.5,
        election: 0.5,
        amendment: 0.66,
      },
      min_endorsements: 0,
      endorsement_bypass_roles: ['admin'],
      quorum_first_call: 0.5,
      quorum_second_call: 0.25,
      quorum_third_call: 0,
      minimum_notice_days: 7,
      quarterly_assembly_required: false,
      extraordinary_quorum: 0.5,
    },
    treasury: {
      mode: 'import',
      locale: 'es-MX',
      currency: 'MXN',
      admin_spending_limit: 30000,
      require_vote_above: 100000,
      clabe: null,
      bank_name: null,
      beneficiary_name: null,
      payment_reference_prefix: null,
      auto_reconciliation: false,
      collection_reminder_days: 0,
      reserva_fund_percentage: 10,
      monthly_statement_auto: true,
    },
    identity: {
      payment_to_vote_enabled: false,
      grace_period_months: 6,
      auto_restore_on_payment: true,
      delinquent_restrictions: [],
      moroso_threshold_ordinary: 6,
      moroso_threshold_extraordinary: 3,
      moroso_notice_days: 0,
      moroso_restrictions: [],
      admin_max_consecutive_terms: 0,
      admin_term_months: 36,
    },
  },
  defaultCategories: [
    { name: 'Diezmos', type: 'income', isSystem: true },
    { name: 'Ofrendas', type: 'income', isSystem: true },
    { name: 'Donaciones', type: 'income', isSystem: false },
    { name: 'Eventos especiales', type: 'income', isSystem: false },
    { name: 'Otros ingresos', type: 'income', isSystem: false },
    { name: 'Salarios y honorarios', type: 'expense', isSystem: false },
    { name: 'Mantenimiento del templo', type: 'expense', isSystem: false },
    { name: 'Servicios (agua, luz)', type: 'expense', isSystem: false },
    { name: 'Misiones y obra social', type: 'expense', isSystem: false },
    { name: 'Eventos litúrgicos', type: 'expense', isSystem: false },
    { name: 'Administración', type: 'expense', isSystem: false },
  ],
  enabledModules: [
    'documents',
    'announcements',
    'calendar',
  ],
  legalFrameworkKey: 'mx.ar',
}
