import type { CommunityPreset } from '../types'

export const residentialPreset: CommunityPreset = {
  type: 'residential',
  displayName: 'Residencial',
  description: 'Condominios, fraccionamientos, colonias cerradas',
  icon: 'building-2',
  labels: {
    member: 'Vecino',
    memberPlural: 'Vecinos',
    contribution: 'Cuota de mantenimiento',
    leader: 'Administrador',
    entity: 'Proveedor',
    community: 'Condominio',
    assembly: 'Asamblea de condóminos',
    oversight: 'Comité de vigilancia',
  },
  defaultRules: {
    governance: {
      default_quorum: 0.5,
      default_majority: 0.5,
      delegation_enabled: true,
      proposal_rights: ['admin', 'comite_vigilancia', 'tesorero', 'miembro'],
      cool_down_hours: 48,
      auto_execution_enabled: false,
      auto_execution_threshold: 0,
      mandatory_discussion_enabled: false,
      default_discussion_hours: 48,
      grace_period_hours: 0,
      quorum_by_type: {
        ordinary: 0.5,
        extraordinary: 0.75,
        budget: 0.5,
        election: 0.5,
        amendment: 0.75,
        gasto: 0.5,
      },
      majority_by_type: {
        ordinary: 0.5,
        extraordinary: 0.66,
        budget: 0.5,
        election: 0.5,
        amendment: 0.66,
        gasto: 0.5,
      },
      min_endorsements: 3,
      endorsement_bypass_roles: ['admin', 'tesorero'],
      quorum_first_call: 0.75,
      quorum_second_call: 0.5001,
      quorum_third_call: 0,
      minimum_notice_days: 7,
      quarterly_assembly_required: true,
      extraordinary_quorum: 0.75,
    },
    treasury: {
      mode: 'import',
      locale: 'es-MX',
      currency: 'MXN',
      admin_spending_limit: 50000,
      require_vote_above: 50000,
      clabe: null,
      bank_name: null,
      beneficiary_name: null,
      payment_reference_prefix: null,
      auto_reconciliation: false,
      collection_reminder_days: 5,
      reserva_fund_percentage: 5,
      monthly_statement_auto: true,
    },
    identity: {
      payment_to_vote_enabled: true,
      grace_period_months: 2,
      auto_restore_on_payment: true,
      delinquent_restrictions: ['vote', 'propose'],
      moroso_threshold_ordinary: 2,
      moroso_threshold_extraordinary: 1,
      moroso_notice_days: 7,
      moroso_restrictions: ['vote', 'be_elected', 'quorum_excluded'],
      admin_max_consecutive_terms: 2,
      admin_term_months: 12,
    },
  },
  defaultCategories: [
    { name: 'Cuotas de mantenimiento', type: 'income', isSystem: true },
    { name: 'Cuotas extraordinarias', type: 'income', isSystem: true },
    { name: 'Intereses moratorios', type: 'income', isSystem: false },
    { name: 'Otros ingresos', type: 'income', isSystem: false },
    {
      name: 'Mantenimiento', type: 'expense', isSystem: false, children: [
        { name: 'Limpieza', type: 'expense', isSystem: false },
        { name: 'Jardinería', type: 'expense', isSystem: false },
        { name: 'Reparaciones', type: 'expense', isSystem: false },
      ]
    },
    { name: 'Servicios (agua, luz, gas)', type: 'expense', isSystem: false },
    { name: 'Seguridad', type: 'expense', isSystem: false },
    { name: 'Administración', type: 'expense', isSystem: false },
    { name: 'Seguros', type: 'expense', isSystem: false },
    { name: 'Fondo de reserva', type: 'expense', isSystem: true },
  ],
  enabledModules: [
    'documents',
    'announcements',
    'calendar',
    'census',
    'residential_units',
    'residential_areas',
    'residential_maintenance',
  ],
  legalFrameworkKey: 'mx.condominio',
}
