import type { CommunityPreset } from '../types'

export const schoolPreset: CommunityPreset = {
  type: 'school',
  displayName: 'Escuela',
  description: 'Escuelas, universidades, sociedades de padres de familia',
  icon: 'graduation-cap',
  labels: {
    member: 'Padre de familia',
    memberPlural: 'Padres de familia',
    contribution: 'Cuota escolar',
    leader: 'Presidente de la mesa directiva',
    entity: 'Proveedor',
    community: 'Escuela',
    assembly: 'Asamblea de padres',
    oversight: 'Comisión de honor y justicia',
  },
  defaultRules: {
    governance: {
      default_quorum: 0.33,
      default_majority: 0.5,
      delegation_enabled: false,
      proposal_rights: ['admin', 'comite_vigilancia', 'miembro'],
      cool_down_hours: 24,
      auto_execution_enabled: false,
      auto_execution_threshold: 0,
      mandatory_discussion_enabled: false,
      default_discussion_hours: 48,
      grace_period_hours: 0,
      quorum_by_type: {
        ordinary: 0.33,
        extraordinary: 0.5,
        budget: 0.5,
        election: 0.5,
        amendment: 0.66,
        gasto: 0.5,
      },
      majority_by_type: {
        ordinary: 0.5,
        extraordinary: 0.5,
        budget: 0.5,
        election: 0.5,
        amendment: 0.66,
        gasto: 0.5,
      },
      min_endorsements: 2,
      endorsement_bypass_roles: ['admin'],
      quorum_first_call: 0.5,
      quorum_second_call: 0.33,
      quorum_third_call: 0,
      minimum_notice_days: 5,
      quarterly_assembly_required: false,
      extraordinary_quorum: 0.5,
    },
    treasury: {
      mode: 'import',
      locale: 'es-MX',
      currency: 'MXN',
      admin_spending_limit: 10000,
      require_vote_above: 30000,
      clabe: null,
      bank_name: null,
      beneficiary_name: null,
      payment_reference_prefix: null,
      auto_reconciliation: false,
      collection_reminder_days: 5,
      reserva_fund_percentage: 0,
      monthly_statement_auto: true,
    },
    identity: {
      payment_to_vote_enabled: false,
      grace_period_months: 1,
      auto_restore_on_payment: true,
      delinquent_restrictions: [],
      moroso_threshold_ordinary: 2,
      moroso_threshold_extraordinary: 1,
      moroso_notice_days: 5,
      moroso_restrictions: [],
      admin_max_consecutive_terms: 1,
      admin_term_months: 12,
    },
  },
  defaultCategories: [
    { name: 'Inscripciones', type: 'income', isSystem: true },
    { name: 'Cuotas mensuales', type: 'income', isSystem: true },
    { name: 'Cuotas extraordinarias', type: 'income', isSystem: false },
    { name: 'Eventos y festivales', type: 'income', isSystem: false },
    { name: 'Donaciones', type: 'income', isSystem: false },
    { name: 'Material didáctico', type: 'expense', isSystem: false },
    { name: 'Mantenimiento de instalaciones', type: 'expense', isSystem: false },
    { name: 'Eventos escolares', type: 'expense', isSystem: false },
    { name: 'Seguridad', type: 'expense', isSystem: false },
    { name: 'Administración', type: 'expense', isSystem: false },
  ],
  enabledModules: [
    'documents',
    'announcements',
    'calendar',
  ],
  legalFrameworkKey: 'mx.ac',
}
